# 编程式事务使用示例
以 `Mysql` 数据库为例。

## 一、准备
### 1) 依赖
```xml
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.11</version>
</dependency>
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-tx</artifactId>
    <version>${spring.version}</version>
</dependency>
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-jdbc</artifactId>
    <version>${spring.version}</version>
</dependency>
```
### 2) DB表准备
```mysql
create table pet (
	id bigint unsigned not null comment '主键',
    pet_name varchar(22) comment '宠物名',
    age int unsigned comment '宠物年龄',
    primary key (id)
) comment '宠物表';
```
### 3) 测试方法准备
后面的测试方法会用到的公共部分。
```java
public class TransactionTest {
    private DataSource dataSource;

    @Before
    public void before() {
        MysqlDataSource mysqlDataSource = new MysqlDataSource();
        mysqlDataSource.setURL("jdbc:mysql://localhost:3306/akira?useUnicode=true&characterEncoding=utf8&useSSL=false");
        mysqlDataSource.setUser("root");
        mysqlDataSource.setPassword("root@Mysql8.0");
        dataSource = mysqlDataSource;
    }

    public void doInsert() {
        // 这里不能直接使用 dataSource.getConnection()，将导致多个sql使用的不是同一个 Connection，无法回滚
        // 不能关闭Connection，因为下个sql还会用到这个Connection，Spring会在commit或rollback时自动关闭。那单独使用这个方法就会导致Connection无法关闭么？而且如果使用了Mybatis等，它会自动关闭Connection吗？
        try {
            Connection con = DataSourceUtils.getConnection(dataSource);
            PreparedStatement ps = con.prepareStatement(STUB_INSERT);
            ps.execute();
        } catch (CannotGetJdbcConnectionException | SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
```

## 二、JDBC事务使用示例
先展示下JDBC是怎样使用事务的。
```java
public class TransactionTest {
    public static final String STUB_INSERT = "insert into pet values (1, 'Tom', 18)";
    
    @Test
    public void test0() throws SQLException {
        Connection con = dataSource.getConnection();
        try (PreparedStatement ps = con.prepareStatement(STUB_INSERT);) {
            con.setAutoCommit(false);

            ps.execute();
            ps.execute(); // Duplicate entry '1' for key 'pet.PRIMARY'

            con.commit();
        } catch (Exception e) {
            con.rollback();
        } finally {
            con.close();
        }
    }
}
```
JDBC的事务 commit 及 rollback 是通过 `Connection` 来实现的。  
这里由于报了异常，因此一条数据也没能插入。

## 三、JdbcTransactionManager使用示例
```java
public class TransactionTest {
    @Test
    public void test1() {
        JdbcTransactionManager txManager = new JdbcTransactionManager(dataSource);
        TransactionStatus transaction = txManager.getTransaction(TransactionDefinition.withDefaults());

        try {
            doInsert();
            doInsert();
            txManager.commit(transaction);
        } catch (Exception e) {
            txManager.rollback(transaction);
        }
    }
}
```

## 四、TransactionTemplate使用示例
```java
public class TransactionTest {
    @Test(expected = RuntimeException.class)
    public void test2() {
        JdbcTransactionManager txManager = new JdbcTransactionManager(dataSource);
        TransactionTemplate template = new TransactionTemplate(txManager);
        
        template.execute(status -> {
            doInsert();
            doInsert();
            return null;
        });
    }
}
```
默认 `RuntimeException` 和 `Error` 才会回滚。

## 总结
这样 Service方法（TransactionTest#doInsert） 就不能关闭 Connection 么？用连接池的情况会怎样呢？